[package]
name = "AptosToken"
version = "1.0.0"
authors = ["Web3 Developer"]

[addresses]
token_addr = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
